### ISSUE TITLE
add Claude v3 Haiku support

### ISSUE THREAD

**Issue by RaphaelDucay** [awslabs/bedrock-vscode-playground#15]

**Comment by RaphaelDucay** [comment]
Hello team ! Are you planing to integrate other ClaudeV3 version than **Sonnet** ? **Haiku** was already released and could be integrated in the extension. It would be a very nice feature since Haiku is a more cost efficient is some typical dev cases. Also **Opus** (the best performer of the Claudev3 family) will be integrated to Bedrock very soon, probably in April (https://www.aboutamazon.com/news/aws/amazon-bedrock-anthropic-ai-claude-3) Are you planning to maintain this extension as new model are made available in Bedrock ? Thanks in advance !

**Comment by bobbywlindsey** [comment]
Hi @RaphaelDucay! We will indeed be adding both Haiku and Opus :) Our goal is to keep this extension up-to-date with any new Bedrock models that come out!
